function   value = CardValue(hand, numHand)
value = 0;


for i=1:numHand
    if      (hand(i,:) == 'Sa')  | ...
            (hand(i,:) == 'Ha')  | ...
            (hand(i,:) == 'Ca')   | ...
            (hand(i,:) == 'Da')
        value = value + 1;
        
    elseif  (hand(i,:) == 'S2')  | ...
            (hand(i,:) == 'H2')  | ...
            (hand(i,:) == 'C2')   | ...
            (hand(i,:) == 'D2')
        value = value + 2;
    elseif  (hand(i,:) == 'S3')  | ...
            (hand(i,:) == 'H3')  | ...
            (hand(i,:) == 'C3')   | ...
            (hand(i,:) == 'D3')
        value = value + 3;
    elseif  (hand(i,:) == 'S4')  | ...
            (hand(i,:) == 'H4')  | ...
            (hand(i,:) == 'C4')   | ...
            (hand(i,:) == 'D4')
        value = value + 4;
    elseif  (hand(i,:) == 'S5')  | ...
            (hand(i,:) == 'H5')  | ...
            (hand(i,:) == 'C5')   | ...
            (hand(i,:) == 'D5')
        value = value + 5;
    elseif  (hand(i,:) == 'S6')  | ...
            (hand(i,:) == 'H6')  | ...
            (hand(i,:) == 'C6')   | ...
            (hand(i,:) == 'D6')
        value = value + 6;
    elseif  (hand(i,:) == 'S7')  | ...
            (hand(i,:) == 'H7')  | ...
            (hand(i,:) == 'C7')   | ...
            (hand(i,:) == 'D7')
            value = value + 7;
    elseif  (hand(i,:) == 'S8')  | ...
            (hand(i,:) == 'H8')  | ...
            (hand(i,:) == 'C8')   | ...
            (hand(i,:) == 'D8')
        value = value + 8;
    elseif  (hand(i,:) == 'S9')  | ...
            (hand(i,:) == 'H9')  | ...
            (hand(i,:) == 'C9')   | ...
            (hand(i,:) == 'D9')
        value = value + 9;
    elseif  (hand(i,:) == 'S1')  | ...
            (hand(i,:) == 'H1')  | ...
            (hand(i,:) == 'C1')   | ...
            (hand(i,:) == 'D1')
        value = value + 10;
    elseif  (hand(i,:) == 'Sj')  | ...
            (hand(i,:) == 'Hj')  | ...
            (hand(i,:) == 'Cj')   | ...
            (hand(i,:) == 'Dj')
        value = value + 10;
     elseif  (hand(i,:) == 'Sq')  | ...
            (hand(i,:) == 'Hq')  | ...
            (hand(i,:) == 'Cq')   | ...
            (hand(i,:) == 'Dq')
        value = value + 10;
    elseif  (hand(i,:) == 'Sk')  | ...
            (hand(i,:) == 'Hk')  | ...
            (hand(i,:) == 'Ck')   | ...
            (hand(i,:) == 'Dk')
        value = value + 10;
    end
    

end